INSERT INTO values_value (value, frequency) VALUES ('Accomplishment', 5);
INSERT INTO values_value (value, frequency) VALUES ('Accountability', 6);
INSERT INTO values_value (value, frequency) VALUES ('Achievement', 7);
INSERT INTO values_value (value, frequency) VALUES ('Activism', 8);
INSERT INTO values_value (value, frequency) VALUES ('Adventure', 9);
INSERT INTO values_value (value, frequency) VALUES ('Affection', 0);
INSERT INTO values_value (value, frequency) VALUES ('Ambition', 0);
INSERT INTO values_value (value, frequency) VALUES ('Autonomy', 0);
INSERT INTO values_value (value, frequency) VALUES ('Challenge', 0);
INSERT INTO values_value (value, frequency) VALUES ('Close relationships', 0);
INSERT INTO values_value (value, frequency) VALUES ('Commitment', 0);
INSERT INTO values_value (value, frequency) VALUES ('Community', 0);
INSERT INTO values_value (value, frequency) VALUES ('Compassion', 0);
INSERT INTO values_value (value, frequency) VALUES ('Competence', 0);
INSERT INTO values_value (value, frequency) VALUES ('Competition', 0);
INSERT INTO values_value (value, frequency) VALUES ('Confidence', 0);
INSERT INTO values_value (value, frequency) VALUES ('Conformity', 0);
INSERT INTO values_value (value, frequency) VALUES ('Control', 0);
INSERT INTO values_value (value, frequency) VALUES ('Coolness under fire', 0);
INSERT INTO values_value (value, frequency) VALUES ('Cooperation', 0);
INSERT INTO values_value (value, frequency) VALUES ('Courage', 0);
INSERT INTO values_value (value, frequency) VALUES ('Creativity', 0);
INSERT INTO values_value (value, frequency) VALUES ('Credibility', 0);
INSERT INTO values_value (value, frequency) VALUES ('Decisiveness', 0);
INSERT INTO values_value (value, frequency) VALUES ('Economic security', 0);
INSERT INTO values_value (value, frequency) VALUES ('Effectiveness', 0);
INSERT INTO values_value (value, frequency) VALUES ('Efficiency', 0);
INSERT INTO values_value (value, frequency) VALUES ('Enthusiasm', 0);
INSERT INTO values_value (value, frequency) VALUES ('Environmentalism', 0);
INSERT INTO values_value (value, frequency) VALUES ('Excellence', 0);
INSERT INTO values_value (value, frequency) VALUES ('Excitement', 0);
INSERT INTO values_value (value, frequency) VALUES ('Fairness', 0);
INSERT INTO values_value (value, frequency) VALUES ('Faith', 0);
INSERT INTO values_value (value, frequency) VALUES ('Fame', 0);
INSERT INTO values_value (value, frequency) VALUES ('Free time', 0);
INSERT INTO values_value (value, frequency) VALUES ('Freedom', 0);
INSERT INTO values_value (value, frequency) VALUES ('Friendships', 0);
INSERT INTO values_value (value, frequency) VALUES ('Growth', 0);
INSERT INTO values_value (value, frequency) VALUES ('Having a family', 0);
INSERT INTO values_value (value, frequency) VALUES ('Health', 0);
INSERT INTO values_value (value, frequency) VALUES ('Helping other people', 0);
INSERT INTO values_value (value, frequency) VALUES ('Helping society', 0);
INSERT INTO values_value (value, frequency) VALUES ('Honesty', 0);
INSERT INTO values_value (value, frequency) VALUES ('Hospitality', 0);
INSERT INTO values_value (value, frequency) VALUES ('Independence', 0);
INSERT INTO values_value (value, frequency) VALUES ('Influence', 0);
INSERT INTO values_value (value, frequency) VALUES ('Inner harmony', 0);
INSERT INTO values_value (value, frequency) VALUES ('Insight', 0);
INSERT INTO values_value (value, frequency) VALUES ('Inspiration', 0);
INSERT INTO values_value (value, frequency) VALUES ('Integrity', 0);
INSERT INTO values_value (value, frequency) VALUES ('Intellectual status', 0);
INSERT INTO values_value (value, frequency) VALUES ('Introspection', 0);
INSERT INTO values_value (value, frequency) VALUES ('Justice', 0);
INSERT INTO values_value (value, frequency) VALUES ('Knowledge', 0);
INSERT INTO values_value (value, frequency) VALUES ('Leadership', 0);
INSERT INTO values_value (value, frequency) VALUES ('Location', 0);
INSERT INTO values_value (value, frequency) VALUES ('Loyalty', 0);
INSERT INTO values_value (value, frequency) VALUES ('Meaningful work', 0);
INSERT INTO values_value (value, frequency) VALUES ('Mentorship', 0);
INSERT INTO values_value (value, frequency) VALUES ('Merit', 0);
INSERT INTO values_value (value, frequency) VALUES ('Money', 0);
INSERT INTO values_value (value, frequency) VALUES ('Movement', 0);
INSERT INTO values_value (value, frequency) VALUES ('Music', 0);
INSERT INTO values_value (value, frequency) VALUES ('Nature', 0);
INSERT INTO values_value (value, frequency) VALUES ('Openness', 0);
INSERT INTO values_value (value, frequency) VALUES ('Order', 0);
INSERT INTO values_value (value, frequency) VALUES ('Patriotism', 0);
INSERT INTO values_value (value, frequency) VALUES ('Peace', 0);
INSERT INTO values_value (value, frequency) VALUES ('Persistance', 0);
INSERT INTO values_value (value, frequency) VALUES ('Personal development', 0);
INSERT INTO values_value (value, frequency) VALUES ('Physical challenge', 0);
INSERT INTO values_value (value, frequency) VALUES ('Pleasure', 0);
INSERT INTO values_value (value, frequency) VALUES ('Power and authority', 0);
INSERT INTO values_value (value, frequency) VALUES ('Privacy', 0);
INSERT INTO values_value (value, frequency) VALUES ('Public service', 0);
INSERT INTO values_value (value, frequency) VALUES ('Purity', 0);
INSERT INTO values_value (value, frequency) VALUES ('Quality', 0);
INSERT INTO values_value (value, frequency) VALUES ('Recognition', 0);
INSERT INTO values_value (value, frequency) VALUES ('Reputation', 0);
INSERT INTO values_value (value, frequency) VALUES ('Responsibility', 0);
INSERT INTO values_value (value, frequency) VALUES ('Romance', 0);
INSERT INTO values_value (value, frequency) VALUES ('Security', 0);
INSERT INTO values_value (value, frequency) VALUES ('Self-knowledge', 0);
INSERT INTO values_value (value, frequency) VALUES ('Self-reliance', 0);
INSERT INTO values_value (value, frequency) VALUES ('Self-respect', 0);
INSERT INTO values_value (value, frequency) VALUES ('Serenity', 0);
INSERT INTO values_value (value, frequency) VALUES ('Sophistication', 0);
INSERT INTO values_value (value, frequency) VALUES ('Spirituality', 0);
INSERT INTO values_value (value, frequency) VALUES ('Stability', 0);
INSERT INTO values_value (value, frequency) VALUES ('Status', 0);
INSERT INTO values_value (value, frequency) VALUES ('Tranquility', 0);
INSERT INTO values_value (value, frequency) VALUES ('Truth', 0);
INSERT INTO values_value (value, frequency) VALUES ('Vibrancy', 0);
INSERT INTO values_value (value, frequency) VALUES ('Volunteering', 0);
INSERT INTO values_value (value, frequency) VALUES ('Wealth', 0);
INSERT INTO values_value (value, frequency) VALUES ('Willpower', 0);
INSERT INTO values_value (value, frequency) VALUES ('Wisdom', 0);